name: Continuous Delivery

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    outputs:
      branch-name: ${{ steps.set-branch-name.outputs.branch-name }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
          cache: "yarn"
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          server-token: ${{ secrets.TURBO_SERVER_TOKEN }}
      - run: yarn install
      - run: yarn run ci
      - run: yarn run docs
      - uses: actions/upload-artifact@v2
        with:
          name: storybooks
          path: |
            packages/fuselage/storybook-static
            packages/fuselage-ui-kit/storybook-static
            packages/onboarding-ui/storybook-static
      - if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            static
      - run: |
          ref='${{ github.ref }}'
          echo "::set-output name=branch-name::$(echo "${ref:11}")"
        id: set-branch-name
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: packages/**/dist/*

  publish-to-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14.17.6"
          registry-url: "https://registry.npmjs.org"
          scope: "@rocket.chat"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            .yarn/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: packages
      - run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn resolve-workspace-deps
        if: github.ref == 'refs/heads/master'
      - run: yarn lerna publish from-package --yes --no-verify-access
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn bump-next
        if: github.ref == 'refs/heads/develop'
      - run: yarn release-next
        if: github.ref == 'refs/heads/develop'
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-to-gh-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    environment:
      name: github-pages
      url: "https://rocketchat.github.io/Rocket.Chat.Fuselage/fuselage/${{ needs.build-and-test.outputs.branch-name }}"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v2
        with:
          name: storybooks
          path: packages
      - if: github.ref == 'refs/heads/master'
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: .
      - run: |
          rm -rf "fuselage/${{ needs.build-and-test.outputs.branch-name }}" "fuselage-ui-kit/${{ needs.build-and-test.outputs.branch-name }}" "onboarding-ui/${{ needs.build-and-test.outputs.branch-name }}"
          mv -v "packages/fuselage/storybook-static" "fuselage/${{ needs.build-and-test.outputs.branch-name }}"
          mv -v "packages/fuselage-ui-kit/storybook-static" "fuselage-ui-kit/${{ needs.build-and-test.outputs.branch-name }}"
          mv -v "packages/onboarding-ui/storybook-static" "onboarding-ui/${{ needs.build-and-test.outputs.branch-name }}"
          rm -rf packages
      - uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .
          commit_message: "Deploy to Github Pages [skip ci]"
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
